### PR TITLE
Sort the elements by key in the IssueFilter

### PR DESCRIPTION
**Pull request by FlorentClarret**
Alphabetically sort the elements by key in the IssueFilter

Members:

| Before | After |
|--------|-------|
|    image |   image |

Teams:

| Before | After |
|--------|-------|
|   image     |     image  |

https://datadoghq.atlassian.net/browse/AITS-296

### CODE REVIEW

**Review by alopezz — APPROVED** [review]
I'm OK with it, but I wonder if it might be better to just sort the entries at widget render time, rather than adding a new dependency. I think that it would probably be here:

https://github.com/DataDog/ddqa/blob/fe906b82a318303838fccd777ccea21b33fa642a/src/ddqa/screens/status.py#L66

**Comment by FlorentClarret** [comment]
> I'm OK with it, but I wonder if it might be better to just sort the entries at widget render time, rather than adding a new dependency. I think that it would probably be here:
> 
> https://github.com/DataDog/ddqa/blob/fe906b82a318303838fccd777ccea21b33fa642a/src/ddqa/screens/status.py#L66

That's what I did at first, however we have another card to add a refresh (maybe auto-refresh) feature to this screen so the render method would be called multiple times and we would then sort it several times. I thought it would be a better approach to change the structure at the cost of a new dependency. We could also sort at render time and cache the result, but we would also need to handle the eviction in case new elements are added. It's a tradeoff I think, but I'm totally OK with your suggestion. What do you think?

**Comment by alopezz** [comment]
I'd say it sounds like premature optimization to me, perhaps. But adding that particular dependency is not a big deal either, so for me it's 👍 .

**Comment by FlorentClarret** [comment]
> I'd say it sounds like premature optimization to me, perhaps. But adding that particular dependency is not a big deal either, so for me it's 👍 .

Agreed. I dropped the dep and we'll see later if this is needed

**Review by alopezz — APPROVED** [review]
👍

**Review by alopezz — APPROVED** [review]

**Pull request merged**
